version: '3.8'

services:
  coordinator1:
    image: zookeeper:3.7
    hostname: coordinator1
    environment:
      ZOO_MY_ID: 1
#      Enable reconfig feature
      ZOO_SERVERS: "server.1=vcm-43196.vm.duke.edu:2888:3888;2181 server.2=vcm-43196.vm.duke.edu:2889:3889;2182"
      ZOO_CFG_EXTRA: "reconfigEnabled=true standaloneEnabled=false skipACL=yes"
#    extra_hosts:
#        - "vcm-43196.vm.duke.edu:127.0.0.1"
    ports:
      - "2181:2181"  # Client port
      - "2888:2888"  # Leader election port
      - "3888:3888"  # Follower port
    network_mode: host


  coordinator2:
    image: zookeeper:3.7
    hostname: coordinator2
    environment:
      ZOO_MY_ID: 2
      #      Enable reconfig feature
      ZOO_SERVERS: "server.1=vcm-43196.vm.duke.edu:2888:3888;2181 server.2=vcm-43196.vm.duke.edu:2889:3889;2182"
      ZOO_CFG_EXTRA: "reconfigEnabled=true standaloneEnabled=false skipACL=yes"
#    extra_hosts:
#      - "vcm-43196.vm.duke.edu:127.0.0.1"
    ports:
      - "2182:2181"  # Client port
      - "2889:2888"  # Leader election port
      - "3889:3888"  # Follower port
    network_mode: host

  follower:
    image: zookeeper:3.7
    hostname: follower
    environment:
      ZOO_MY_ID: ${node_id}
      ZOO_SERVERS: "server.1=vcm-43196.vm.duke.edu:2888:3888;2181 server.2=vcm-43196.vm.duke.edu:2889:3889;2182 server.${node_id}=${node_address}:2888:3888:observer;2181"
      ZOO_CFG_EXTRA: "reconfigEnabled=true standaloneEnabled=false skipACL=yes"
#      Set this follower as an observer
    ports:
      - "2181:2181"  # Client port
      - "2888:2888"  # Leader election port
      - "3888:3888"  # Follower port
    network_mode: host

  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - node_address=${node_address}
      - node_id=${node_id}
      - is_leader=${is_leader}

#networks:
#  zk_net: